sudo: false

language: php

php:
  - 7.1
  - 7.2
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_script:
  - composer require php-coveralls/php-coveralls:^2.1.0 squizlabs/php_codesniffer:^3.3.2 -n
  - composer install -n

script:
  - mkdir -p build/logs && phpunit --coverage-clover build/logs/clover.xml
  - vendor/bin/phpunit
  - vendor/bin/phpcs

after_script:
  - php vendor/bin/coveralls -v
